= Docker Redis VLab
Koukaras1806 <koukaras1806@example.com>
:toc:
:toc-title: Περιεχόμενα
:icons: font

== Περιγραφή

Αυτό το εικονικό εργαστήριο (VLab) δημιουργεί ένα περιβάλλον Docker για την εκτέλεση μιας υπηρεσίας Redis. 
Το εργαστήριο έχει σχεδιαστεί για να παρέχει έναν εύκολο τρόπο ανάπτυξης και δοκιμής του Redis σε απομονωμένο περιβάλλον.

== Χαρακτηριστικά

- **Docker**: Χρησιμοποιείται για την πακετοποίηση της εφαρμογής και την εξασφάλιση της φορητότητας και της απομόνωσης.
- **Redis**: Ένας δημοφιλής και ταχύς in-memory key-value store που χρησιμοποιείται ευρέως για caching και message brokering.

== Οδηγίες Εγκατάστασης

=== Προαπαιτούμενα

- Docker εγκατεστημένο στο σύστημά σας. Μπορείτε να το κατεβάσετε από https://docs.docker.com/get-docker/[εδώ].

=== Βήματα Εγκατάστασης

.Κλωνοποίηση του αποθετηρίου
----
git clone https://github.com/koukaras1806/my-docker-redis-vlab.git
cd my-docker-redis-vlab
----

.Κατασκευή της Docker εικόνας
----
sudo docker build -t my-redis .
----

.Εκτέλεση του Docker container
----
sudo docker run -d -p 6379:6379 my-redis
----

.Επιβεβαίωση ότι το container εκτελείται
----
sudo docker ps
----

.Σύνδεση στο Redis
----
sudo docker exec -it <container_id> redis-cli
----
Αντικαταστήστε το `<container_id>` με το πραγματικό ID του container που εκτελείται, το οποίο μπορείτε να βρείτε από την έξοδο της εντολής `docker ps`.

== Εργαλεία και Υπηρεσίες που χρησιμοποιήθηκαν

- **Docker**: Για την πακετοποίηση και εκτέλεση της εφαρμογής.
- **Redis**: Για την παροχή υπηρεσιών in-memory key-value store.

== Αντιμετώπιση Προβλημάτων

Αν αντιμετωπίσετε οποιοδήποτε πρόβλημα κατά τη διάρκεια της εγκατάστασης ή της εκτέλεσης του container, μπορείτε να ελέγξετε τα logs του Docker:

----
sudo docker logs <container_id>
----

Εάν το πρόβλημα συνεχίζεται, βεβαιωθείτε ότι έχετε εγκατεστημένη την τελευταία έκδοση του Docker και ότι έχετε ακολουθήσει όλα τα βήματα σωστά.
